src/Entity/Dinosaur.php
<?php

namespace App\Entity;

use App\Enum\HealthStatus;

class Dinosaur
{
    private string $name;
    private string $genus;
    private int $length;
    private string $enclosure;
    private HealthStatus $health = HealthStatus::Healthy;

    public function __construct(string $name, string $genus = 'Unknown', int $length = 0, string $enclosure = 'Unknown')
    {
        $this->name = $name;
        $this->genus = $genus;
        $this->length = $length;
        $this->enclosure = $enclosure;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getGenus(): string
    {
        return $this->genus;
    }

    public function getLength(): int
    {
        return $this->length;
    }

    public function getEnclosure(): string
    {
        return $this->enclosure;
    }

    public function getSizeDescription(): string
    {
        if (10 <= $this->length) {
            return 'Large';
        }
        if (4 < $this->length) {
            return 'Medium';
        }

        return 'Small';
    }

    /**
     * @return string
     */
    public function getHealth(): HealthStatus
    {
        return $this->health;
    }

    /**
     * @param string $health
     */
    public function setHealth(HealthStatus $health): void
    {
        //$this->health = HealthStatus::Healthy->value === $health ? HealthStatus::Healthy : HealthStatus::Sick;
        $this->health = $health;
    }

    public function isAcceptingVisitors(): bool
    {
        return HealthStatus::Sick !== $this->health;
    }


}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Dinosaur;
use App\Service\GithubService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @throws \Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface
     */
    #[Route(path: '/', name: 'main_controller', methods: ['GET'])]
    public function index(GithubService $githubService): Response
    {
        $dinos = [
            new Dinosaur('Daisy', 'Velociraptor', 2, 'Paddock A'),
            new Dinosaur('Maverick','Pterodactyl', 7, 'Aviary 1'),
            new Dinosaur('Big Eaty', 'Tyrannosaurus', 15, 'Paddock C'),
            new Dinosaur('Dennis', 'Dilophosaurus', 6, 'Paddock B'),
            new Dinosaur('Bumpy', 'Triceratops', 10, 'Paddock B'),
        ];

        foreach ($dinos as $dino) {
            $dino->setHealth($githubService->getHealthReport($dino->getName()));
        }

        return $this->render('main/index.html.twig', [
            'dinos' => $dinos,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome to Dinotopia!{% endblock %}</title>
        <link rel="stylesheet" href="{{ asset('styles/styles.css') }}">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/fab65cceab.js" crossorigin="anonymous"></script>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
    {% block body %}
    {% endblock %}
    </body>
</html>

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container volcano mt-4" style="flex-grow: 1;">
    <h1 class="mt-5">Dinotopia Status</h1>
    <div class="dino-stats-container mt-2 p-3">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Genus</th>
                <th>Size</th>
                <th>Enclosure</th>
                <th>Accepting Visitors</th>
            </tr>
            </thead>
            <tbody>
            {% for dino in dinos %}
                <tr>
                    <td>{{ dino.name }}</td>
                    <td>{{ dino.genus }}</td>
                    <td>{{ dino.sizeDescription }}</td>
                    <td>{{ dino.enclosure }}</td>
                    <td>{{ dino.acceptingVisitors ? 'Oui' : 'Non' }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="https://github.com/SymfonyCasts/dino-park" target="_blank" class="mb-3 me-2 mb-md-0 text-decoration-none lh-1 text-light">
                <p><i>GenLab Secret Dino Repository</i></p>
            </a>
        </div>

        <div class="col-md-4 d-flex justify-content-center align-items-center">
            <a href="https://symfonycasts.com/" class="mb-3 me-2 mb-md-0 text-light text-decoration-none lh-1">
                <p>With ❤️ from the gals and guys at SymfonyCasts</p>
            </a>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-light" href="https://github.com/SymfonyCasts"><i class="fab fa-github"></i></a></li>
            <li class="ms-3"><a class="text-light" href="https://twitter.com/symfonycasts"><i class="fab fa-twitter"></i></a></li>
            <li class="ms-3"><a class="text-light" href="https://www.facebook.com/SymfonyCasts/"><i class="fab fa-facebook"></i></a></li>
        </ul>
    </footer>
</div>
{% endblock %}